name: orcamento_app
description: App de orçamentos com PDF, login local e integração n8n.
publish_to: "none"
version: 1.0.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.3
  http: ^1.2.2
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.4.2
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  mask_text_input_formatter: ^2.9.0
  font_awesome_flutter: 10.7.0
  package_info_plus: ^8.0.0
  file_picker: ^8.0.3
  crypto: ^3.0.3
  flutter_secure_storage: ^9.2.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon.png
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf

# Ícone do aplicativo
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#0F1115"
  adaptive_icon_foreground: "assets/icon.png"
